services:
  - type: web
    plan: free
    name: url
    env: python
    buildCommand: pip3 install -U -r requirements.txt
    startCommand: python bot.py
    repo: https://github.com/Kushalhk/url.git      
    branch: main
    envVars:
      - key: BOT_TOKEN 
        sync: false
      - key: API_ID 
        sync: false
      - key: API_HASH 
        sync: false
      - key: FORCE_SUB 
        sync: false
      - key: DATABASE_NAME
        sync: false
      - key: DATABASE_URL 
        sync: false 
      - key: PICS 
        sync: false
      - key: ADMINS
        sync: false    
      - key: LOG_CHANNEL
        sync: false
    autoDeploy: false 
